### ISSUE TITLE
No function parameter completion at all（C++)

### ISSUE THREAD

**Issue by NanerLee** [aidistan/atom-symbols-view-plus#7]
In my C++ file, there is a function 
![2016-12-10 10-18-27](https://cloud.githubusercontent.com/assets/16791509/21070540/2c50a61e-bec2-11e6-93b3-6f0e13a103e2.png)

And it can be completed
![2016-12-10 10-17-33](https://cloud.githubusercontent.com/assets/16791509/21070544/4cd6c4c2-bec2-11e6-9f99-6533a29714bb.png)

But it don't include any function parameter.

**Comment by aidistan** [comment]
It is said that `autocomplete-plus` supports function parameter completion already. (atom/autocomplete-plus#455)

After checking the API reference, I found we have to dynamically generate snippets as the auto completion suggestions instead of texts, which is hard for CTAG-based providers, since CTAG is designed for capturing tags without arguments. 

Thanks for trying this package and I'm sorry this generic provider can only support limited auto completion functions.

---

For function parameter completion in C++, you could try the `autocomplete-clang` package which built based on a c language family powerful compiler named `clang`.

**Comment by NanerLee** [comment]
> since CTAG is designed for capturing tags without arguments.

But when I see the .tags file, ctags captures the arguments of function. And I uses Universal Ctags.
like this:
![2016-12-12 09-36-52](https://cloud.githubusercontent.com/assets/16791509/21085557/8b5aa226-c04e-11e6-8a37-7476425f47f9.png)

And with same .tags file. one package named atom-ctags can complete function arguments.
![2016-12-12 09-45-16](https://cloud.githubusercontent.com/assets/16791509/21085685/b78fded2-c04f-11e6-801a-069d7b371bbe.png)

**Comment by aidistan** [comment]
Those are just line patterns recorded in the `.tags` file for symbol searching, which is useless for argument extraction actually.

Though function argument completion in `atom-ctags` is a little primitive (like not allow users to tab through function arguments), I have implemented it in `v0.113.2-plus.2`. 

Thanks for your suggestion and hope the update will be helpful~

**Comment by NanerLee** [comment]
Thanks for your so fast reply.

Now the package has met my needs, but there is a little suggestion. Can you display the return type of function in the list ? Of course, when we press tab, the return type shouldn't be completed.

**Comment by aidistan** [comment]
Sure thing. Have been published as `0.113.2-plus.3`.

**Comment by NanerLee** [comment]
Thanks. You're the most hard-working developer I've ever seen.
